### ISSUE TITLE
Reproduce the best results of the DeepMistake Team for LSCDiscovery

### ISSUE THREAD

**Issue by arshandalili** [ChangeIsKey/LSCDBenchmark#50] opened 2024-09-10 15:02 UTC
**Reproduce results from [this page](https://github.com/Daniil153/DM-in-Spanish-LSCDiscovery)**:
- Run DM+APD on the original test subset of dwug_es (push results to a shared table)
- Find how to integrate pre-calculated pairs of usages
- Reproduce the results for compare, spearman and JSD, spearman metrics (and add these metrics if they are not there)
- Create an integration test_dm_lscdiscovery

**Comment by Garrafao** [comment] 2024-09-12 16:38
The possibility to run the benchmark in "inference mode" (without evaluation) is described in the readme:
https://github.com/ChangeIsKey/LSCDBenchmark/blob/f14714fc678891199d7b61a1492ffaec3d170611/README.md?plain=1#L69

**Comment by nvanva** [comment] 2024-09-27 11:51
@arshandalili Arshan, before closing issues could you please describe how exactly they were solved. For this issue please cite a command we can use to reproduces the results in the benchmark.

**Closed by nvanva** 2024-09-27 11:51 UTC

**Comment by arshandalili** [comment] 2024-09-28 20:16
Reproduced LSCDiscovery COMPARE Result.

COMPARE:

![Screenshot 2024-09-28 at 10 15 56 PM](https://github.com/user-attachments/assets/008e997b-9c21-4f75-896c-7902fbaee941)


DWUG_ES LSCD_Graded:

![Screenshot 2024-09-28 at 10 14 18 PM](https://github.com/user-attachments/assets/0f4b5b2d-a085-47d2-8d48-67b1293438ba)

**Comment by nvanva** [comment] 2024-09-30 13:33
@arshandalili Could you please give a link to these tests in the repo. Please also link where the reproduced results were published, I don't see any models giving COMPARE scores of  -0.858 or 0.858 in our paper or repository. We should clearly specify which results we are trying to reproduce here, and if we see any difference how much this difference is.

**Comment by arshandalili** [comment] 2024-09-30 20:11
The reference is [LSCDiscovery](https://github.com/Daniil153/DM-in-Spanish-LSCDiscovery), which has 0.854 COMP Spearman. In the benchmark, we got 0.858, which is roughly equal. The reason for the difference could be the data, but it is very unlikely that the model is not working well.

**Comment by arshandalili** [comment] 2024-10-02 13:43
@nvanva Please try running without `pytest`. [test_lscd.py](https://github.com/ChangeIsKey/LSCDBenchmark/blob/main/test_lscd.py) file is for running the task directly and doesn't have assertions for testing. For that refer to integration tests. Moreover, [line 99](https://github.com/ChangeIsKey/LSCDBenchmark/blob/b75eead0ae33a44900bc4ea879253fb48475b4ac/src/wic/DM.py#L99) of DM.py has set the model to run on GPU, in which you didn't use. So to solve this issue, you'll have to run the  [test_lscd.py](https://github.com/ChangeIsKey/LSCDBenchmark/blob/main/test_lscd.py) without pytest and modify the [line 99](https://github.com/ChangeIsKey/LSCDBenchmark/blob/b75eead0ae33a44900bc4ea879253fb48475b4ac/src/wic/DM.py#L99) `device = 'cuda' if torch.cuda.is_available() else 'cpu'`. I can change it.

**Comment by nvanva** [comment] 2024-10-02 15:11
@arshandalili Arshan, have you checked that it works from a freshly cloned repo? Could you please check it and send the stdout? Probably it will not fit a single screenshot, so do redirection ```python test_lscd.py &> outputs.txt```) and send outputs.txt!
I've spent 2 hours and fixed lots of small technical issues but still doesn't get the result, cannot spend on that more. 
Just a few issues I remember from this struggle:
1) sentence_transformers is not in the requirements.txt
2) failure because the directory "results" does not exist, please commit it to the repo (without its content and subdirectories)
3) mlrose==1.3.0 cannot be installed without additional flags to pip because it depends on sklear==0.0

**Comment by nvanva** [comment] 2024-10-02 17:10
@arshandalili please also make sure that installation instructions work and we have all necessary dependendencies installed by them in a fresh virtual env

**Comment by nvanva** [comment] 2024-10-02 18:19
Ok, after manually installing dependencies the code is running. But the final score is 0.08
![image](https://github.com/user-attachments/assets/c9fed3ab-47b0-4f08-b51c-15d4af9c8ce9)

**Comment by nvanva** [comment] 2024-10-03 14:58
Finally after fixing requirements.txt and other technical issues mentioned above I was able to reproduce the score 0.85 shown above. The problem is it is reproduced only when installing DM from a fork of the DM repo by @arshandalili . If after reproducing I install DM from the official repo I get awful score of 0.08 instead . This probably means that the official repo is not broken. Arshan, please fix this, as we discussed several times before we need working DM in the official repo and we want input that one in the benchmark, not some fork.

**Comment by arshandalili** [comment] 2024-10-03 18:08
@nvanva I have already opened a PR for the merge, but is open as of now. [PR](https://github.com/nvanva/deepmistake/pull/4). Please review it.

**Comment by nvanva** [comment] 2024-10-04 09:00
@arshandalili PR is merged, the results are now reproduced: 
![image](https://github.com/user-attachments/assets/b7f8979b-9490-4651-b615-7c4390541f3a)

Thank you for fixing that!

**Comment by arshandalili** [comment] 2024-10-04 10:21
@nvanva You're welcome!

**Comment by Garrafao** [comment] 2024-10-05 08:11
@arshandalili Before closing the issue, please make sure that the test also runs for lscd_graded.

**Comment by sachinn12** [comment] 2025-01-27 18:45
The results have been reproduced.Commit:https://github.com/ChangeIsKey/LSCDBenchmark/commit/80afca8c5f80f07bbf19b6bea9e050cfff5dca0a
